server:
  port: 9000

spring:
  application:
    name: rosex-authorization-server

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.security: info
